
version: 2
jobs:
 build:
   env:
      DOCKER_IMAGE_NAME: x64/fmf:latest
      DOCKER_FILE_PATH: ./docker/Dockerfile
   machine: true
   steps:
     - checkout
     - name: Build Docker
     - run: |
          docker build . --file /docker/Dockerfile --tag  x64/fmf:latest
