version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: x64/fmf-on-ci
    docker:
      - image: x64/fmf:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build . --file ./docker/Dockerfile --tag $IMAGE_NAME:latest 
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
