name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Build/Tests
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        cd docker && ./build.sh

  deployment:
    name: Deployment
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        run: |
          echo "deploy is OK!"
